name: Continuous Build

on:
  push:
    paths:
      - src/**
      - test/**

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run test coverage
    steps:
      # https://gitversion.net/docs/reference/requirements
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build solution
        run: dotnet build --configuration Release /p:ContinuousIntegrationBuild=true
        
      - name: Test solution
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --collect "XPlat Code Coverage" --results-directory "./test-results"

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Results
          path: test-results/*.trx    # Path to test results
          reporter: dotnet-trx    # Format of test results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./test-results/
          verbose: true